### ISSUE TITLE
Possible to integrate social media coverage? 

### ISSUE THREAD

**Issue by suenjedt** [thor-project/dashboard#18]
e.g. https://twitter.com/project_thor_eu?

**Comment by eamonnmag** [comment]
At what level? Like altmetric level?

**Comment by suenjedt** [comment]
Ah sorry. I had only thought about the comms part (e.g. on the events page), but of course you are very right. we probably could go further and look into altmetrics (but that is not urgent, I would say).

**Comment by almereyda** [comment]
In that sense, the Dashboard could pick up where [the Next Edge Report](https://github.com/Connoropolous/The-Next-Edge-Report) left off: Providing a singular, time-based interface to community activity throughout the streams. The notion of location in then just extended into the virtual realm.

Is it possible to run only the events page, or even use third party data providers for different views? Graphana/InfluxDB and Prometheus come to mind, while community activity is not to be found in commercial Social Media advertisement platforms, but also within the IndieWeb, plenty of Discourses and mailing lists.

The events page visualisation just asks for more integrations, that for sure.
