### ISSUE TITLE
change "unknown" doi object type label to "unspecified"

### ISSUE THREAD

**Issue by daslerr** [thor-project/dashboard#22]
On the DataCite stats tab, the "unknown" label under DOI Object Type is being mistaken for a controlled category term. "Unspecified" indicates that the info wasn't there to retrieve.

**Comment by eamonnmag** [comment]
This is actually what I get back from DataCite. do you want me to just change the label?

**Comment by daslerr** [comment]
No, if that's what you actually get back from DataCite, then don't change it. I thought it was just some kind of catchall label.
