### ISSUE TITLE
visualization: resizing/lower resolution

### ISSUE THREAD

**Issue by daslerr** [thor-project/dashboard#8]
1. When resizing the window or viewing at lower resolutions, is there a good way to minimize scrolling to the right while preserving the chart elements? Some of the larger charts either don't resize or drop a piece (like the breakdown on the ORCID map) when they're resized.
2. On the research object tab (blue), when resizing the window the charts fall out of their bounding boxes. (See screenshot.) 
   <img width="307" alt="graphscreenshot" src="https://cloud.githubusercontent.com/assets/3181623/11184312/1eec0cb2-8c77-11e5-9c80-3007e7508834.png">

**Comment by eamonnmag** [comment]
I can try to make this work, but responsive plots is a bit difficult, especially for some of the plots we show such as the big overview graph. But I'll try to make it look good!
