### ISSUE TITLE
style: update logo

### ISSUE THREAD

**Issue by daslerr** [thor-project/dashboard#9]
The logo in the prototype should be replaced with the current THOR logo. The white text version is attached. 
![thor_logo_white_small](https://cloud.githubusercontent.com/assets/3181623/11238904/1c11ac5e-8de9-11e5-97b9-1b14d60ffd5a.png)

**Comment by eamonnmag** [comment]
It will look pretty terrible. I kept the overall look of the logo in the current style, but the colour change shouldn't be a big deal. Logos can have different versions.

**Comment by daslerr** [comment]
According to the communications plan for the project, this is the logo we're supposed to use on all outputs. But I have a stacked version that will fit a bit more nicely. I'll email it. (svg)
